name: LaTeX Build

on:
  push:
    branches:
      - main  # Trigger this workflow on push event on main branch

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Build LaTeX document
      run: |
        docker run --mount src=$GITHUB_WORKSPACE,target=/repo,type=bind \
            -w /repo \
            ubuntu:22.04 \
            bash -c 'pdflatex -output-directory=/repo main.tex'

    - name: Upload PDF artifact
      uses: actions/upload-artifact@v2
      with:
        name: compiled-pdf
        path: main.pdf
