name: LaTeX Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Documents to compile
        run: |
          # List files that shall be compiled. The ".tex" _must_ be ommited.
          # Paths are relative to the project root.
          TEX_FILES=("main" "subfolder/extra")

          # This is the bind path inside the container.
          BPATH="/latex"

          # Generate .tex filenames relative to BPATH.
          # This usualy may not be changed manually.
          COMPILE_FILES=()
          for texfile in "${TEX_FILES[@]}"; do
            FILE="${BPATH}/${texfile}.tex"
            COMPILE_FILES+=("$FILE")
            if ! [[ -f "$FILE" ]]; then
                echo "Error, ${FILE} is not a valid file or path to a .tex file!"
            fi
          done

          # Generate .pdf filenames relative to BPATH used for creating the
          # outputs, i.e. the PDFs and the artifacts & the release.
          OUPUT_FILES=()
          for texfile in "${TEX_FILES[@]}"; do
            OUTPUT_FILES+=("${BPATH}/${texfile}.pdf")
          done

      - name: Build LaTeX documents
        run: |
          docker pull rearrangedletters/latex-full
          docker run -dt --name=texy --mount type=bind,source="${PWD}",target="/latex" rearrangedletters/latex-full
          
          # Remove and re-install the packages with the desired version here.
          # The pattern is as follows:
          # sudo tlmgr remove <package-name>
          # sudo tlmgr install <package-name>=<version>
          # It is essential to first remove the packge, because if the given version
          # is older than the currently installed one, then tlmgr will not downgrade it.

          docker exec -d texy mkdir "${BPATH}/out"

          for file in "${COMPILE_FILES[@]}"
          do
            for i in {1..3}; do   # This runs the compilation 3 times
              echo "this is another echo: $file"
              docker exec -d texy pdflatex --output-directory="${BPATH}/out" "$file"
            done
          done

          # Move compiled PDFs outside the container.
          for output in "${OUTPUT_FILES[@]}"
          do
            docker exec -d texy cp "${BPATH}/out"
          done

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v3
        with:
          name: pdf-artifacts
          path: "${BPATH}/out/"

      - name: Publish PDFs as a release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "${PWD}/out/"
          makeLatest: true
          tag: "latest"
          allowUpdates: true
