name: LaTeX Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build LaTeX document
        run: |
          docker pull rearrangedletters/latex
          docker run --rm -v $PWD:/latex rearrangedletters/latex pdflatex latex/main.tex

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v2
        with:
          name: compiled-pdf
          path: latex/main.pdf

