name: LaTeX Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build LaTeX document
        run: |
          docker pull rearrangedletters/latex-full
          docker run -d -t --name=texy -v $PWD:/latex rearrangedletters/latex-full
          # Remove and re-install the packages with the desired version here.
          docker exec -d texy pdflatex --output-directory=/latex /latex/main.tex
          docker exec -d texy pdflatex --output-directory=/latex /latex/main.tex
          docker exec -d texy pdflatex --output-directory=/latex /latex/main.tex
          docker exec -d texy cp /latex/main.pdf
          # docker run $PWD:/latex rearrangedletters/latex-full sh -c "pdflatex --output-directory=/latex /latex/main.tex && cp /latex/main.pdf ."

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v2
        with:
          name: main.pdf
          path: main.pdf

      - name: Publish PDF as Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "main.pdf"
          makeLatest: true
          tag: "latest"
