name: LaTeX Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up build environment
        run: |
          docker run --mount src=$GITHUB_WORKSPACE,target=/repo,type=bind \
            -w /repo \
            ubuntu:22.04 \
            bash -c 'apt-get update && \
                     apt-get install -y texlive-full tzdata && \
                     ln -fs /usr/share/zoneinfo/Asia/Kolkata /etc/localtime && \
                     dpkg-reconfigure --frontend noninteractive tzdata'

      - name: Build LaTeX document
        run: |
          docker run --mount src=$GITHUB_WORKSPACE,target=/repo,type=bind \
            -w /repo \
            ubuntu:22.04 \
            pdflatex -output-directory=/repo main.tex

      # - name: Fix versions of specific LaTeX packages
      #   run: |
      #     docker run --mount src=$GITHUB_WORKSPACE,target=/repo,type=bind \
      #       -w /repo \
      #       bash -c 

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v2
        with:
          name: compiled-pdf
          path: main.pdf

